[[constraint]]
  branch = "master"
  name = "github.com/bitrise-io/go-steputils"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/hendych/fast-archiver"
